config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :author, presence: true
	validates :year, presence: true
	validates :genre, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	# before_action :set_book, only: [:show, :edit, :delete, :update]

	def index 
		@books = Book.all
	end

	def new 
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)

		if @book.save 
			redirect_to root_path, notice: "Book was successfully added." 
		else
			render :new, alert: "Your book was not successfully saved."
		end
	end

	def edit
		# raise params

		@book = Book.find_by(id: params[:id])
	end


	def update 
		@book = Book.find_by(id: params[:id])

		if @book
			@book.update!(book_params)
			redirect_to root_path, notice: "Book was successfully updated." 
		else
			render :edit, alert: "Your book was not successfully updated."
		end
	end

	def destroy
		@book = Book.find_by(id: params[:id])

		if @book
			@book.destroy
			redirect_to root_path, notice: "Book was successfully deleted."

		else
			redirect_to root_path, alert: "Book was not successfully deleted."
		end	
	end



private

def book_params
	params.require(:book).permit(:title, :author, :year, :genre)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class = "booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Your Book Details</h1>
	<%= simple_form_for @book do |f| %>
		<%= f.input :title %>
		<%= f.input :author %>
		<%= f.input :year %>
		<%= f.input :genre %>
		<br />
		
		<%= f.submit 'Update', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/books/index.html.erb
<% @books.each do |book| %>
	<div class= "booyah-box col-xs-10 col-xs-offset-1">
		<h1><%= book.title %></h1>
		<i><%= book.author %></i><br />
		<i><%= book.year %></i><br />
		<i><%= book.genre %></i><br />

		<%= link_to 'Edit', [:edit, book], class: 'btn btn-primary' %>
		<%= link_to 'Delete', book_path(book), method: :delete, class: 'btn btn-primary' %>

	</div>

<% end %> 	

app/views/books/new.html.erb
<div class = "booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Your Book Details</h1>
	<%= simple_form_for @book do |f| %>
		<%= f.input :title %>
		<%= f.input :author %>
		<%= f.input :year %>
		<%= f.input :genre %>
		<br />
		
		<%= f.submit 'Create', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

 <body>
	<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
   
      <%= link_to 'Library', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
	      <li>
        	<%= link_to new_book_path do %>
        		<i class="glyphicon glyphicon-plus-sign"></i>
        		New Book
        		<% end %>
      	</li>	

        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


    <%= yield %>
	</body>
</html>